#!/bin/bash

# Reusable
BUILD_DIR=$SDIR/../klin/ver-nodejs/build/js/packages/ver-nodejs-app/kotlin
GRADLE_DIR=$SDIR/../klin/ver-nodejs
KLIN_SRC_DIR=$SDIR/../klin/ver-nodejs/app/src/commonMain/kotlin/org/opengamestudio
SRC_DIR=$SDIR/../src

# Replace a line in a file
function replace {
    file=$1
    was=$2
    now=$3
    cmd="sed -i.backup 's|$was|$now|g' $file"
    eval "$cmd"
    rm $file.backup
}
