#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

T=$SDIR/step
source $SDIR/other

STEP=0
# Build Klin in case it's not yet built
source $T/buildKlin
# Proceed with tests
source $T/generateTestKD
source $T/buildTest
source $T/runTest
