#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

T=$SDIR/step
source $SDIR/other

STEP=0
# Rebuild Klin just in case
source $T/embedKDFiles
source $T/build
source $T/generateKlinKD

# Proceed with tests
source $T/generateTestKD
