#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

T=$SDIR/step
source $SDIR/other

STEP=0
# Build Klin just in case it wasn't yet built
source $T/buildKlin

# Proceed with tests
source $T/generateTestKD
#source $T/stripTestKDJS
source $T/buildTest
source $T/runTest
