#!/bin/bash

STEP=$((STEP+1))
echo -e "\n> > > > Step №$STEP. Distribute Klin"
DIST_DIR=$SDIR/../dist
cp $BUILD_DIR/app.js $DIST_DIR
cp $BUILD_DIR/kotlin-kotlin-stdlib.js $DIST_DIR
cp $BUILD_DIR/ver-nodejs-app.js $DIST_DIR
