/**
 * This file is a part of Kotlin dialect:
 *     https://github.com/OGStudio/kotlin-dialect
 * License: CC0
 * Version: 2.0.0
 */

package org.opengamestudio

const val TEMPLATE_CPP_CONTEXT_HEADER = """
class %NAME%Context {
    public:
        %NAME%Context(KTRef(%NAME%Context) ctx): ctx(ctx) { }

%ITEMS%

    private:
        KTRef(%NAME%Context) ctx;
};
"""
const val TEMPLATE_CPP_CONTEXT_ITEM_BOOL_HEADER = """
        bool %FIELD%();
"""
const val TEMPLATE_CPP_CONTEXT_ITEM_BOOL_SOURCE = """
bool %NAME%::%FIELD%() {
    return KT.%NAME%.get_%FIELD%(ctx);
}
"""
const val TEMPLATE_CPP_CONTEXT_ITEM_INT_HEADER = """
        int %FIELD%();
"""
const val TEMPLATE_CPP_CONTEXT_ITEM_INT_SOURCE = """
int %NAME%::%FIELD%() {
    return KT.%NAME%.get_%FIELD%(ctx);
}
"""
const val TEMPLATE_CPP_CONTEXT_ITEM_STRING_HEADER = """
        QString %FIELD%() const &;
"""
const val TEMPLATE_CPP_CONTEXT_ITEM_STRING_SOURCE = """
QString %NAME%::%FIELD%() const & {
    const char *raw = KT.%NAME%.get_%FIELD%(ctx);
    QString str(raw);
    KTSym->DisposeString(raw);
    return str;
}
"""
const val TEMPLATE_CPP_CONVERSIONS = """
// Convert Bool to Any (for SDK)
fun boolToAny(item: Boolean): Any {
    return item as Any
}

// Convert String to Any (for SDK)
fun strToAny(item: String): Any {
    return item as Any
}
"""
const val TEMPLATE_CPP_EFFECTS_HEADER = """
class %NAME%EffectRegistry {
    public:
        static void processOneliners();
        static void registerOneliners(
            KTRef(KDController) ctrl,
            const std::vector<std::any> &items
        );

    private:
        static std::vector<std::any> _items;
};
"""
const val TEMPLATE_CPP_EFFECTS_SOURCE = """
std::vector<std::any> %NAME%EffectRegistry::_items;

void %NAME%EffectRegistry::processOneliners() {
    auto %PREFIX%Ctx = KT.%PREFIX%CtrlCtx();
    auto recentField = KT.%PREFIX%CtrlCtxField();

    int halfCount = _items.size() / 2;
    for (int i = 0; i < halfCount; ++i) {
        auto effectField = std::any_cast<const char *>(_items[i * 2]);
        if (strcmp(effectField, recentField) == 0) {
            auto callback = std::any_cast<std::function<void(%NAME%Context)>>(_items[i * 2 + 1]);
            auto c = %NAME%Context(%PREFIX%Ctx);
            callback(c);
        }
    }

    KTSym->DisposeString(recentField);
}

void %NAME%EffectRegistry::registerOneliners(
    KTRef(KDController) ctrl,
    const std::vector<std::any> &items
) {
    // This should only be run once. Yes, it's ugly
    // but it keeps API consistent with other platforms.
    KT.registerCallbackC(
        ctrl,
        (void *)&%NAME%EffectRegistry::processOneliners
    );
    _items = items;
}
"""
const val TEMPLATE_CPP_EXTENSIONS = """
// Register C callback into KDController
@OptIn(ExperimentalForeignApi::class)
fun KDController.registerCallbackC(cb: CPointer<CFunction<() -> Unit>>) {
    callbacks.add({ c -> cb() })
}
"""
const val TEMPLATE_CPP_HEADER_END = """
#endif // KLIN_AUTOGENERATED_CPP_HEADER_H
"""
const val TEMPLATE_CPP_HEADER_START = """
#ifndef KLIN_AUTOGENERATED_CPP_HEADER_H
#define KLIN_AUTOGENERATED_CPP_HEADER_H

#include <any>
#include <string>
#include <QObject>
#include <QString>
#include "KT.h"
"""
const val TEMPLATE_CPP_SET_HEADER = """template<typename T> void %PREFIX%Set(const std::string &key, T value);
"""
const val TEMPLATE_CPP_SET_SOURCE = """template<> void %PREFIX%Set(
    const std::string &key,
    bool value
) {
    KT.KDController.set(KT.%PREFIX%Ctrl(), key.c_str(), KT.boolToAny(value));
}

template<> void %PREFIX%Set(
    const std::string &key,
    const char *value
) {
    KT.KDController.set(KT.%PREFIX%Ctrl(), key.c_str(), KT.strToAny(value));
}
"""
const val TEMPLATE_CPP_SOURCE_START = """
#include "ignore.kd.h"
#include "KT.h"
"""

const val TEMPLATE_FOBJ_CPP = """
// Special structure to reference keys with a compile time check
struct FStruct {
%FSTRUCT_ITEMS%
};
inline FStruct F;

// Special structure to reference keys in QML
class FObj: public QObject {
    Q_OBJECT
%PROPERTY_ITEMS%

    public:
        FObj(): QObject() { }
%IMPL_ITEMS%
};
"""
const val TEMPLATE_FOBJ_CPP_FSTRUCT_ITEM = """    static inline constexpr const char *%NAME% = "%NAME%";
"""
const val TEMPLATE_FOBJ_CPP_IMPL_ITEM = """        QString key_%NAME%() const { return F.%NAME%; }
"""
const val TEMPLATE_FOBJ_CPP_PROPERTY_ITEM = """    Q_PROPERTY(QString %NAME% READ key_%NAME% CONSTANT)
"""
const val TEMPLATE_FOBJ_KOTLIN = """
// Special object to reference context fields with a compile time validation
@JsExport
object F {
%ITEMS%
}
"""
const val TEMPLATE_FOBJ_KOTLIN_ITEM = """    const val %NAME% = "%NAME%"
"""
const val TEMPLATE_FOBJ_SWIFT = """
// Special object to reference context fields with a compile time validation
struct F {
%ITEMS%
}
"""
const val TEMPLATE_FOBJ_SWIFT_ITEM = """    static let %NAME% = "%NAME%"
"""

const val TEMPLATE_KOTLIN_CONTEXT = """
%COMMENT%
%PREFIX%
data class %NAME%(
%FIELDS%
    override var recentField: String = "",
): KDContext {
    override fun <T> field(name: String): T {
%GETTERS%        }
        return "unknown-field-name" as T
    }

    override fun selfCopy(): KDContext {
        return this.copy()
    }

    override fun setField(
        name: String,
        value: Any?
    ) {
%SETTERS%        }
    }
}
"""

const val TEMPLATE_KOTLIN_CONTEXT_GETTER = """        } else if (name == "%NAME%") {
            return %NAME% as T
"""

const val TEMPLATE_KOTLIN_CONTEXT_GETTER_FIRST = """        if (name == "%NAME%") {
            return %NAME% as T
"""

const val TEMPLATE_KOTLIN_CONTEXT_SETTER = """        } else if (name == "%NAME%") {
            %NAME% = value as %TYPE%
"""

const val TEMPLATE_KOTLIN_CONTEXT_SETTER_FIRST = """        if (name == "%NAME%") {
            %NAME% = value as %TYPE%
"""

const val TEMPLATE_KOTLIN_FIELD = "    var %NAME%: %TYPE% = %DEFAULT%,"

const val TEMPLATE_KOTLIN_STRUCT = """
%COMMENT%
%PREFIX%
data class %NAME%(
%FIELDS%
) {}
"""
